"""THE entry point of this repository: a library generated by a trained transformer language model.

This is a SEPARATE ENTRY from the order-2 Markov submission, which the competition rules permit:
"If a team has two or more sufficiently different models, it may submit one entry per model." A
4-layer autoregressive transformer and a dipeptide Markov chain are different models by any reading.
The Markov entry is its own repository, https://github.com/braxtonmensah/amp-challenge-2027-entry.

WHY A SEPARATE REPOSITORY RATHER THAN A SECOND SCRIPT NAME. The organizers' validator hardcodes
`ENTRY_POINT = "generate"` and reads `<repo>/generate/library.fasta`. A second entry point named
anything else is never invoked, so two models in one repository would regenerate the same library
twice and the second entry would collapse into a duplicate of the first without any error. One
repository per model is the only arrangement the validator can actually distinguish.

WHY BOTH. Measured on the organizers' own seqme scorer against a disjoint half of the reference set,
the two libraries win different metrics and the Phase 1 aggregation weights are withheld, so there is
no way to know which the grader prefers:

    library              Diversity  Conformity      FBD       MMD
    real AMPs (ceiling)     0.856      0.489      0.00486   0.00050
    order-2 Markov          0.852      0.583      0.00889   0.00115
    transformer (this)      0.858      0.490      0.00568   0.00097

The transformer is better on diversity, FBD (36% closer to the reference distribution) and MMD, and it
lands on 0.490 conformity, which is essentially the real-AMP value of 0.489. The Markov chain scores
0.583, i.e. MORE conforming than real peptides are. Rather than guess which the withheld weights reward,
both are submitted.

WHY THE SMALL MODEL. A larger transformer (d=256, 6 layers, 4.76M parameters) reached a better best
validation perplexity, 6.93 against 7.72, but its train loss fell to 1.21 while validation rose to 2.10,
a 0.88 gap with validation degrading after its peak. That is memorisation, and its library measured a
WORSE MMD (0.00156) than even the Markov chain. Bigger lost. The shipped model is 0.81M parameters.

DENSITY-MODEL COMPARISON, same corpus and same held-out split:
    uniform random over 20 residues   perplexity 20.00
    order-2 Markov chain              perplexity 14.79
    this transformer                  perplexity  7.72

DETERMINISM. Sampling is forced onto the CPU even when a GPU is present, because CUDA and CPU draw from
different random streams and the organizers re-run this entry point and byte-compare the output. Leaving
a GPU idle is the intended trade: a reproducible library is worth more here than a fast one.

The rules say reproducibility is checked by running `uv sync` and this entry point "on a Linux
workstation with a single GPU" and comparing against the submitted library -- a DIFFERENT machine from
the one that produced the submission. For a transformer that is a real hazard, and it is not
hypothetical: WE MEASURED IT FAILING.

In float32, with one seed and the same torch version (2.14.0), Windows (+cpu build) and Linux (+cu130
build) produced libraries that differed in exactly one sequence of 50,000:

    Windows: NLVQFEMQILGQLTINAIENPQPK W QHLQR
    Linux:   NLVQFEMQILGQLTINAIENPQPK S QHLQK

The 24-residue prefix is shared, so a single sampled token flipped and the rest of that sequence
followed. The mechanism is not mysterious. Each token compares a drawn uniform against a cumulative
distribution over 23 tokens; matrix-multiply reduction order differs between builds, perturbing logits
at float32's ~1e-7 scale; a flip happens whenever the draw lands within that band of a boundary. Across
~1.5 million token draws, one such near-tie is about what you would expect.

Two consecutive runs on ONE machine were byte-identical, in float32 and in float64, and thread count 1
versus 8 made no difference. So the failure is specifically cross-machine, and "two runs agree here"
would have concealed it.

THE FIX IS float64 SAMPLING, which shrinks the perturbation to ~1e-16 and the expected flips per
library to ~1e-10. It costs about 2.4x in time and buys the only property this entry actually claims.
Getting there also required fixing a latent bug in `lm.py`: the causal mask was built without a dtype,
so it stayed float32 while the model moved to float64, which silently changed the model's output
distribution by 0.14 in probability rather than merely rounding it.

TIMING, measured rather than guessed: 14 minutes end to end on 8 Linux cores in float32, roughly 2.4x
that in float64, and about 4x slower again on Windows. ~56,800 draws yield 50,000 unique novel
sequences, an 88% keep rate after the length, duplicate and reference filters.

TRAINING DATA. `data/antibacterial.fasta` only, the corpus shipped in the competition template. No
pretrained weights, no external sequences. Trained weights ship in `checkpoint/peptide_lm.pt`.
"""
from __future__ import annotations

import argparse
import os
import tempfile
from pathlib import Path

import torch
import torch.nn.functional as F

from amp.generate import mean_hydrophobicity, net_charge, pick_top, read_fasta
from amp.lm import BOS, EOS, ITOS, MAXLEN, PAD, PeptideLM

SEED = 20260930


def _write_fasta(seqs, path):
    """Write atomically, so a killed process leaves NO file rather than a plausible fragment.

    An earlier run of this script was killed mid-write and left a 300-sequence library.fasta that looked
    like a valid result. Write to a temp file in the same directory, fsync, then rename.
    """
    path = str(path)
    directory = os.path.dirname(path) or "."
    fd, tmp = tempfile.mkstemp(dir=directory, suffix=".partial")
    try:
        with os.fdopen(fd, "w", newline="\n") as fh:
            for i, s in enumerate(seqs, start=1):
                fh.write(">seq%d\n%s\n" % (i, s))
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


@torch.no_grad()
def sample_library(ckpt, ref_path, n, seed=SEED, batch=512, temperature=1.0):
    """Sample `n` unique sequences that are 8-50 aa and absent from the reference set.

    Forced to CPU for reproducibility: see the module docstring.
    """
    ck = torch.load(ckpt, map_location="cpu", weights_only=False)
    model = PeptideLM(**ck["cfg"])
    model.load_state_dict(ck["state"])
    # float64, and this is a REPRODUCIBILITY requirement rather than an accuracy one. See the module
    # docstring: in float32 this library diverged across two machines in exactly one sequence of
    # 50,000. Each sampled token compares a drawn uniform against a cumulative distribution, so a
    # logit perturbation of float32's order (~1e-7) flips a token whenever the draw lands that close
    # to a boundary; over ~1.5 million token draws such a near-tie is expected. float64 shrinks that
    # perturbation to ~1e-16, putting the expected number of flips per library near 1e-10.
    model.eval().to(torch.float64)
    torch.manual_seed(seed)

    refs = read_fasta(ref_path)
    refset = set(refs)

    out, seen, drawn = [], set(), 0
    while len(out) < n and drawn < n * 40:
        idx = torch.full((batch, 1), BOS, dtype=torch.long)
        done = torch.zeros(batch, dtype=torch.bool)
        for _ in range(MAXLEN - 1):
            logits = model(idx)[:, -1, :] / temperature
            logits[:, PAD] = float("-inf")
            logits[:, BOS] = float("-inf")
            nxt = torch.multinomial(F.softmax(logits, dim=-1), 1)
            nxt[done] = EOS
            idx = torch.cat([idx, nxt], dim=1)
            done |= nxt.squeeze(1) == EOS
            if bool(done.all()):
                break
        drawn += batch
        for row in idx.tolist():
            s = "".join(ITOS[t] for t in row[1:] if t in ITOS)
            if not (8 <= len(s) <= 50) or s in seen or s in refset:
                continue
            seen.add(s)
            out.append(s)
            if len(out) >= n:
                break
        if drawn % (batch * 10) == 0:
            print("  drawn %d, kept %d ..." % (drawn, len(out)), flush=True)

    if len(out) < n:
        raise RuntimeError("only sampled %d of %d unique novel sequences in %d draws"
                           % (len(out), n, drawn))
    return out, refs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-sequences", type=int, default=50_000)
    ap.add_argument("--top-k", type=int, default=100)
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--ckpt", default="./checkpoint/peptide_lm.pt")
    ap.add_argument("--ref", default="./data/antibacterial.fasta")
    ap.add_argument("--batch", type=int, default=512)
    a = ap.parse_args()

    out_dir = Path("generate")
    out_dir.mkdir(parents=True, exist_ok=True)

    print("sampling %d sequences from %s on CPU (deterministic)" % (a.n_sequences, a.ckpt), flush=True)
    seqs, refs = sample_library(a.ckpt, a.ref, a.n_sequences, seed=a.seed, batch=a.batch)
    _write_fasta(seqs, out_dir / "library.fasta")
    print("library: %d sequences -> %s" % (len(seqs), out_dir / "library.fasta"), flush=True)

    # identical selection machinery to the Markov entry: measured envelope, composition guard with
    # cysteine excluded, internal diversity cap, and the three-definition identity screen.
    top = pick_top(seqs, refs, a.top_k)
    _write_fasta(top, out_dir / "top.fasta")
    print("top:     %d sequences -> %s" % (len(top), out_dir / "top.fasta"), flush=True)

    qs = [net_charge(t) for t in top]
    hs = [mean_hydrophobicity(t) for t in top]
    print("top-100 net charge   median %+.1f  range %+.1f to %+.1f"
          % (sorted(qs)[len(qs) // 2], min(qs), max(qs)))
    print("top-100 hydrophobic. median %+.2f  range %+.2f to %+.2f"
          % (sorted(hs)[len(hs) // 2], min(hs), max(hs)))
    print("top-1 %s" % top[0])


if __name__ == "__main__":
    main()
